name: "Local LLM Stack"

services:

  open-webui:
    image: ${OPEN_WEBUI_IMAGE}
    platform: linux/arm64
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False
      - ENV=dev
      - AUDIO_TTS_ENGINE=openai
      - AUDIO_TTS_MODEL=tts-1
      - AUDIO_TTS_VOICE=af_sky
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://host.docker.internal:8880/v1
      - AUDIO_TTS_OPENAI_API_KEY=${AUDIO_TTS_OPENAI_API_KEY:-not-needed}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-itsasecret}
    networks:
      - local-llm-network
    ports:
      - 3000:8080
    restart: unless-stopped

  kokoro-tts:
    image: ${KOKORO_TTS_IMAGE}
    platform: linux/arm64
    ports:
      - 8880:8880
    restart: always
    networks:
      - local-llm-network

networks:
  local-llm-network:

volumes:
  open-webui:

  
  